/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GraciasRouteImport } from './routes/gracias'
import { Route as ApiPreguntasRouteImport } from './routes/api/preguntas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GraciasRoute = GraciasRouteImport.update({
  id: '/gracias',
  path: '/gracias',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPreguntasRoute = ApiPreguntasRouteImport.update({
  id: '/api/preguntas',
  path: '/api/preguntas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gracias': typeof GraciasRoute
  '/api/preguntas': typeof ApiPreguntasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gracias': typeof GraciasRoute
  '/api/preguntas': typeof ApiPreguntasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gracias': typeof GraciasRoute
  '/api/preguntas': typeof ApiPreguntasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/gracias' | '/api/preguntas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gracias' | '/api/preguntas'
  id: '__root__' | '/' | '/gracias' | '/api/preguntas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GraciasRoute: typeof GraciasRoute
  ApiPreguntasRoute: typeof ApiPreguntasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gracias': {
      id: '/gracias'
      path: '/gracias'
      fullPath: '/gracias'
      preLoaderRoute: typeof GraciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/preguntas': {
      id: '/api/preguntas'
      path: '/api/preguntas'
      fullPath: '/api/preguntas'
      preLoaderRoute: typeof ApiPreguntasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GraciasRoute: GraciasRoute,
  ApiPreguntasRoute: ApiPreguntasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
